# SPDX-License-Identifier: GPL-3.0-only
"""Bounded original /trial protocol over existing retrieval and routing modules."""
import argparse,json,logging,re,time,uuid
from pathlib import Path
from types import SimpleNamespace
from http.server import BaseHTTPRequestHandler,HTTPServer
from urllib.parse import urlsplit
import bot,model_query,named_routing,multistate_routing,route_adapter
from retrieval_support import route_intent,route_reply
from local_visuals import artifact_config,export,print_routes
class Rejection(ValueError):
 def __init__(self,code):self.code=code;super().__init__(code)

def normalized(msgs):
 if not isinstance(msgs,list) or not 1<=len(msgs)<=300:raise Rejection('messages_shape')
 out=[]
 for m in msgs:
  if not isinstance(m,dict):raise Rejection('messages_shape')
  if m.get('role') not in ('user','assistant'):continue
  v=m.get('content')
  if isinstance(v,list):
   if not all(isinstance(x,dict) and x.get('type')=='text' and isinstance(x.get('text'),str) for x in v):raise Rejection('text_only')
   v=''.join(x['text'] for x in v)
  if not isinstance(v,str):raise Rejection('text_only')
  if m['role']=='assistant':
   # Exact presentation suffix generated by our Pipe, not arbitrary text truncation.
   v=re.sub(r'\n\n(?:\[[A-Z][0-9]+\] [^\n]*\n?)*\n\nTrial: [0-9]+ input tokens; [0-9.]+s\. Deterministic tool selection\.$','',v)
  v=v.strip()
  if len(v)>(12000 if m['role']=='assistant' else 2000):raise Rejection('text_bound')
  if not v:raise Rejection('text_only')
  out.append({'role':m['role'],'content':v})
 if not out or out[-1]['role']!='user':raise Rejection('messages_shape')
 return out

class Application:
 def __init__(self,root,model,ollama_url,profile="tiny"):
  u=urlsplit(ollama_url)
  if u.scheme!='http' or u.hostname!='127.0.0.1' or u.path!='/api/chat' or u.username or u.password or u.query or u.fragment:raise ValueError('Local Ollama URL required')
  self.root=Path(root).resolve();self.model=model;self.url=ollama_url;self.profile=profile;self.pending={}
 def run(self,body):
  start=time.monotonic()
  if not isinstance(body,dict):raise Rejection('messages_shape')
  history=normalized(body.get('messages'));q=history[-1]['content'];s=print_routes.scope(body)
  sources=[];tokens=0;retrieval_status=None
  previous=self.pending.get(s)
  if previous and time.time()-previous['time']>86400:
   self.pending.pop(s,None);previous=None
  routing=route_intent(q) or route_reply(q,previous['request'] if previous else None,self.root/'navigation')
  if not routing:self.pending.pop(s,None)
  printed=print_routes.dispatch(q,s)
  if printed:answer=printed['direct']
  elif q.lower().startswith('calc:'):
   from compact_context import calculate
   answer=str(calculate(q.split(':',1)[1].strip()))
  elif q.lower().startswith(('read:','search:','reference:','files:')):
   result=bot.retrieve(self.root,q);sources=result['sources'];retrieval_status=result.get('status')
   answer='\n\n'.join('['+v['id']+'] '+v['text'] for v in sources) or result.get('message') or 'No matching excerpt.'
   if sources and result.get('message'):answer+='\n\nLibrary notice: '+result['message']
  elif q.lower().startswith('guide:') or re.search(r'\b(illustrated|leaflet)\b',q,re.I):
   answer='Illustrated Guide exports are not included in this source alpha. Use Read: with an exact document filename for source excerpts.'
  elif routing:
   print_routes.clear(s)
   previous=self.pending.pop(s,None)
   if previous and time.time()-previous['time']>86400:previous=None
   pending=previous['request'] if previous else None
   try:
    request=multistate_routing.parse(q,pending if pending and pending.get('action')=='trip' else None) or named_routing.parse_request(q,self.root/'navigation',pending)
    if not request:answer='Legacy Map dispatch is not included; use named settlement directions with an explicit region.'
    elif request.get('awaiting') and request.get('awaiting')!='trip':
     if s:
      if len(self.pending)>=128:self.pending.pop(next(iter(self.pending)))
      self.pending[s]={'request':request,'time':time.time()}
     answer=request.get('message') or 'Specify the missing region or endpoints for the route.'
    else:
     sources,result,answer=route_adapter.execute(request,self.root/'navigation')
     answer+=print_routes.save(s,result)
   except (OSError,ValueError,KeyError,RuntimeError):answer='The local map or routing runtime is unavailable; no route was calculated.'
  else:
   if len(q)>400:raise Rejection('text_bound')
   found=bot.retrieve(self.root,q);sources=found['sources'];retrieval_status=found.get('status')
   if not sources or (retrieval_status or {}).get('index_status') in {'missing','unreadable','legacy_unverified'}:
    answer='\n\n'.join('['+v['id']+'] '+v['text'] for v in sources)
    answer+=(('\n\n' if answer else '')+(found.get('message') or 'No matching excerpt.'))
   else:
    model_query.HERE=bot.library.safe(self.root,'local-qa/guides.sqlite').parent
    model_query.MODEL=self.model
    def retrieve(_):
     return [{'id':v['id'],'title':v['source'],'file':v['source'],'location':v['source'],'date':'unverified','text':v['text']} for v in sources]
    model_query.retrieve=retrieve
    result=model_query.query(SimpleNamespace(question=q,search=None,retrieve_only=False,num_gpu=0,threads=4,ollama_url=self.url,profile=self.profile))
    answer=result['answer'];tokens=result.get('input_tokens') or 0
    sources=[{'id':v['id'],'source':v['location'],'text':v['text']} for v in result['sources']]
    if found.get('message'):answer+='\n\nLibrary notice: '+found['message']
  return {'answer':answer,'context':{'memory':[],'summary':[],'tool_results':sources},'retrieval_status':retrieval_status,'prompt_tokens':tokens,'seconds':round(time.monotonic()-start,3)}

def make_server(app,port=8769):
 class Handler(BaseHTTPRequestHandler):
  def log_message(self,*args):pass
  def do_GET(self):
   if export.serve(self):return
   if self.path!='/health':self.send_error(404);return
   self.respond({'status':'ok','interface':'source-alpha'},200)
  def do_HEAD(self):
   if not export.serve(self,head=True):self.send_error(404)
  def respond(self,value,status):
   out=json.dumps(value).encode();self.send_response(status);self.send_header('Content-Type','application/json');self.send_header('Content-Length',str(len(out)));self.end_headers();self.wfile.write(out)
  def do_POST(self):
   rid=uuid.uuid4().hex[:12]
   try:
    if self.path!='/trial' or self.headers.get('Origin') or self.headers.get_all('Host')!=['127.0.0.1:'+str(self.server.server_port)]:raise Rejection('unsupported_tool')
    n=int(self.headers.get('Content-Length','0'))
    if not 1<=n<=180000:raise Rejection('text_bound')
    self.connection.settimeout(5)
    result=app.run(json.loads(self.rfile.read(n)));status=200
   except Exception as exc:
    code=exc.code if isinstance(exc,Rejection) else 'internal'
    logging.warning('adapter_reject request_id=%s code=%s category=%s',rid,code,type(exc).__name__)
    result={'error':code,'request_id':rid,'answer':'Local request rejected ['+code+'; '+rid+'].'};status=400
   self.respond(result,status)
 server=HTTPServer(('127.0.0.1',port),Handler)
 export.BASE=artifact_config.BASE='http://127.0.0.1:'+str(server.server_port)+'/artifacts/'
 return server

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--root',type=Path,required=True);p.add_argument('--model',required=True);p.add_argument('--profile',choices=['tiny','standard'],default='tiny');p.add_argument('--port',type=int,default=8769);p.add_argument('--artifacts',type=Path,default=Path('runtime/artifacts'));p.add_argument('--ollama-url',default='http://127.0.0.1:11434/api/chat');a=p.parse_args()
 if a.artifacts.is_symlink():raise ValueError('Artifact directory must not be a symlink')
 a.artifacts.mkdir(parents=True,exist_ok=True,mode=0o700)
 export.ART=artifact_config.ART=a.artifacts.resolve()
 with make_server(Application(a.root,a.model,a.ollama_url,a.profile),a.port) as server:server.serve_forever()
if __name__=='__main__':main()
